### ISSUE TITLE
Why is my program all displayed after running This error

### ISSUE THREAD

**Issue by dshfjsd** [DerekDardzinski/vaspvis#6]
'grep' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:/Users/10157/PycharmProjects/pythonProject2/dos.py", line 4, in <module>
    bs = Band(folder=r'C:\Users\10157\Desktop\band')
  File "C:\Users\10157\PycharmProjects\pythonProject2\venv\lib\site-packages\vaspvis\band.py", line 120, in __init__
    self.efermi = float(os.popen(f'grep E-fermi {os.path.join(folder, "OUTCAR")}').read().split()[2]) + shift_efermi
IndexError: list index out of range

**Comment by DerekDardzinski** [comment]
Usually this error occurs if your calculation did not completely finish. Double check your OUTCAR to see if everything completed normally and that "E-fermi" is present in the file.

**Comment by dshfjsd** [comment]
Thank you so much

**Comment by Yicie** [comment]
I sorry to ask again but I thought I met the same problem. I did checked the OUTCAR and  E-fermi :  -0.1906     XC(G=0):  -5.7341     alpha+bet : -5.1756 were in the OUTCAR file normally. Could there be any other solution to this situation?
